api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--aoai
        value: '{{ .Env.AOAI_CONNECTIONSTRING }}'
      - name: connectionstrings--chat-model-id
        value: '{{ .Env.AOAI_CHAT_MODEL_DEPLOYMENT_ID }}'
      - name: connectionstrings--embedding-model-id
        value: '{{ .Env.AOAI_EMBEDDING_MODEL_DEPLOYMENT_ID }}'
  template:
    containers:
      - image: {{ .Image }}
        name: chatclient
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: services__agentapi__http__0
            value: http://agentapi.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__agentapi__https__0
            value: https://agentapi.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: ConnectionStrings__aoai
            secretRef: connectionstrings--aoai
          - name: ConnectionStrings__chat-model-id
            secretRef: connectionstrings--chat-model-id
          - name: ConnectionStrings__embedding-model-id
            secretRef: connectionstrings--embedding-model-id
    scale:
      minReplicas: 1
tags:
  azd-service-name: chatclient
  aspire-resource-name: chatclient
